# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import nanopb_pb2
import commontypes_pb2
import rpc_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='daemon.proto',
  package='barobo.Daemon',
  serialized_pb='\n\x0c\x64\x61\x65mon.proto\x12\rbarobo.Daemon\x1a\x0cnanopb.proto\x1a\x11\x63ommontypes.proto\x1a\trpc.proto\"3\n\x0bTcpEndpoint\x12\x16\n\x07\x61\x64\x64ress\x18\x01 \x02(\tB\x05\x92?\x02\x08@\x12\x0c\n\x04port\x18\x02 \x02(\r\"\x93\x01\n\x0fresolveSerialId\x1a(\n\x02In\x12\"\n\x08serialId\x18\x01 \x02(\x0b\x32\x10.barobo.SerialId\x1aV\n\x06Result\x12\x1e\n\x06status\x18\x01 \x02(\x0e\x32\x0e.barobo.Status\x12,\n\x08\x65ndpoint\x18\x02 \x02(\x0b\x32\x1a.barobo.Daemon.TcpEndpoint\".\n\x0b\x63ycleDongle\x1a\x15\n\x02In\x12\x0f\n\x07seconds\x18\x01 \x02(\r\x1a\x08\n\x06Result\"n\n\rsendRobotPing\x1a\x33\n\x02In\x12-\n\x0c\x64\x65stinations\x18\x01 \x03(\x0b\x32\x10.barobo.SerialIdB\x05\x92?\x02\x10\x08\x1a(\n\x06Result\x12\x1e\n\x06status\x18\x01 \x02(\x0e\x32\x0e.barobo.Status\"b\n\x0b\x64ongleEvent\x12\x1e\n\x06status\x18\x01 \x02(\x0e\x32\x0e.barobo.Status\x12\x33\n\x0f\x66irmwareVersion\x18\x02 \x02(\x0b\x32\x1a.barobo.rpc.VersionTriplet\"\xcb\x01\n\nrobotEvent\x12\"\n\x08serialId\x18\x01 \x02(\x0b\x32\x10.barobo.SerialId\x12\x33\n\x0f\x66irmwareVersion\x18\x02 \x02(\x0b\x32\x1a.barobo.rpc.VersionTriplet\x12.\n\nrpcVersion\x18\x03 \x02(\x0b\x32\x1a.barobo.rpc.VersionTriplet\x12\x34\n\x10interfaceVersion\x18\x04 \x02(\x0b\x32\x1a.barobo.rpc.VersionTriplet')




_TCPENDPOINT = descriptor.Descriptor(
  name='TcpEndpoint',
  full_name='barobo.Daemon.TcpEndpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='address', full_name='barobo.Daemon.TcpEndpoint.address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\222?\002\010@')),
    descriptor.FieldDescriptor(
      name='port', full_name='barobo.Daemon.TcpEndpoint.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=126,
)


_RESOLVESERIALID_IN = descriptor.Descriptor(
  name='In',
  full_name='barobo.Daemon.resolveSerialId.In',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='serialId', full_name='barobo.Daemon.resolveSerialId.In.serialId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=148,
  serialized_end=188,
)

_RESOLVESERIALID_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='barobo.Daemon.resolveSerialId.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='barobo.Daemon.resolveSerialId.Result.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endpoint', full_name='barobo.Daemon.resolveSerialId.Result.endpoint', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=276,
)

_RESOLVESERIALID = descriptor.Descriptor(
  name='resolveSerialId',
  full_name='barobo.Daemon.resolveSerialId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_RESOLVESERIALID_IN, _RESOLVESERIALID_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=276,
)


_CYCLEDONGLE_IN = descriptor.Descriptor(
  name='In',
  full_name='barobo.Daemon.cycleDongle.In',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='seconds', full_name='barobo.Daemon.cycleDongle.In.seconds', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=293,
  serialized_end=314,
)

_CYCLEDONGLE_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='barobo.Daemon.cycleDongle.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=198,
)

_CYCLEDONGLE = descriptor.Descriptor(
  name='cycleDongle',
  full_name='barobo.Daemon.cycleDongle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_CYCLEDONGLE_IN, _CYCLEDONGLE_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=278,
  serialized_end=324,
)


_SENDROBOTPING_IN = descriptor.Descriptor(
  name='In',
  full_name='barobo.Daemon.sendRobotPing.In',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='destinations', full_name='barobo.Daemon.sendRobotPing.In.destinations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\222?\002\020\010')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=343,
  serialized_end=394,
)

_SENDROBOTPING_RESULT = descriptor.Descriptor(
  name='Result',
  full_name='barobo.Daemon.sendRobotPing.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='barobo.Daemon.sendRobotPing.Result.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=230,
)

_SENDROBOTPING = descriptor.Descriptor(
  name='sendRobotPing',
  full_name='barobo.Daemon.sendRobotPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_SENDROBOTPING_IN, _SENDROBOTPING_RESULT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=326,
  serialized_end=436,
)


_DONGLEEVENT = descriptor.Descriptor(
  name='dongleEvent',
  full_name='barobo.Daemon.dongleEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='barobo.Daemon.dongleEvent.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='firmwareVersion', full_name='barobo.Daemon.dongleEvent.firmwareVersion', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=438,
  serialized_end=536,
)


_ROBOTEVENT = descriptor.Descriptor(
  name='robotEvent',
  full_name='barobo.Daemon.robotEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='serialId', full_name='barobo.Daemon.robotEvent.serialId', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='firmwareVersion', full_name='barobo.Daemon.robotEvent.firmwareVersion', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rpcVersion', full_name='barobo.Daemon.robotEvent.rpcVersion', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='interfaceVersion', full_name='barobo.Daemon.robotEvent.interfaceVersion', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=539,
  serialized_end=742,
)

_RESOLVESERIALID_IN.fields_by_name['serialId'].message_type = commontypes_pb2._SERIALID
_RESOLVESERIALID_IN.containing_type = _RESOLVESERIALID;
_RESOLVESERIALID_RESULT.fields_by_name['status'].enum_type = commontypes_pb2._STATUS
_RESOLVESERIALID_RESULT.fields_by_name['endpoint'].message_type = _TCPENDPOINT
_RESOLVESERIALID_RESULT.containing_type = _RESOLVESERIALID;
_CYCLEDONGLE_IN.containing_type = _CYCLEDONGLE;
_CYCLEDONGLE_RESULT.containing_type = _CYCLEDONGLE;
_SENDROBOTPING_IN.fields_by_name['destinations'].message_type = commontypes_pb2._SERIALID
_SENDROBOTPING_IN.containing_type = _SENDROBOTPING;
_SENDROBOTPING_RESULT.fields_by_name['status'].enum_type = commontypes_pb2._STATUS
_SENDROBOTPING_RESULT.containing_type = _SENDROBOTPING;
_DONGLEEVENT.fields_by_name['status'].enum_type = commontypes_pb2._STATUS
_DONGLEEVENT.fields_by_name['firmwareVersion'].message_type = rpc_pb2._VERSIONTRIPLET
_ROBOTEVENT.fields_by_name['serialId'].message_type = commontypes_pb2._SERIALID
_ROBOTEVENT.fields_by_name['firmwareVersion'].message_type = rpc_pb2._VERSIONTRIPLET
_ROBOTEVENT.fields_by_name['rpcVersion'].message_type = rpc_pb2._VERSIONTRIPLET
_ROBOTEVENT.fields_by_name['interfaceVersion'].message_type = rpc_pb2._VERSIONTRIPLET
DESCRIPTOR.message_types_by_name['TcpEndpoint'] = _TCPENDPOINT
DESCRIPTOR.message_types_by_name['resolveSerialId'] = _RESOLVESERIALID
DESCRIPTOR.message_types_by_name['cycleDongle'] = _CYCLEDONGLE
DESCRIPTOR.message_types_by_name['sendRobotPing'] = _SENDROBOTPING
DESCRIPTOR.message_types_by_name['dongleEvent'] = _DONGLEEVENT
DESCRIPTOR.message_types_by_name['robotEvent'] = _ROBOTEVENT

class TcpEndpoint(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TCPENDPOINT
  
  # @@protoc_insertion_point(class_scope:barobo.Daemon.TcpEndpoint)

class resolveSerialId(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class In(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESOLVESERIALID_IN
    
    # @@protoc_insertion_point(class_scope:barobo.Daemon.resolveSerialId.In)
  
  class Result(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _RESOLVESERIALID_RESULT
    
    # @@protoc_insertion_point(class_scope:barobo.Daemon.resolveSerialId.Result)
  DESCRIPTOR = _RESOLVESERIALID
  
  # @@protoc_insertion_point(class_scope:barobo.Daemon.resolveSerialId)

class cycleDongle(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class In(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CYCLEDONGLE_IN
    
    # @@protoc_insertion_point(class_scope:barobo.Daemon.cycleDongle.In)
  
  class Result(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CYCLEDONGLE_RESULT
    
    # @@protoc_insertion_point(class_scope:barobo.Daemon.cycleDongle.Result)
  DESCRIPTOR = _CYCLEDONGLE
  
  # @@protoc_insertion_point(class_scope:barobo.Daemon.cycleDongle)

class sendRobotPing(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class In(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SENDROBOTPING_IN
    
    # @@protoc_insertion_point(class_scope:barobo.Daemon.sendRobotPing.In)
  
  class Result(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SENDROBOTPING_RESULT
    
    # @@protoc_insertion_point(class_scope:barobo.Daemon.sendRobotPing.Result)
  DESCRIPTOR = _SENDROBOTPING
  
  # @@protoc_insertion_point(class_scope:barobo.Daemon.sendRobotPing)

class dongleEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DONGLEEVENT
  
  # @@protoc_insertion_point(class_scope:barobo.Daemon.dongleEvent)

class robotEvent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROBOTEVENT
  
  # @@protoc_insertion_point(class_scope:barobo.Daemon.robotEvent)

# @@protoc_insertion_point(module_scope)
